// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFDpnIPg2FJT33T_dbYbdB9UcuWJR9Kc',
    appId: '1:813007988453:web:8957fbeab15c6b1f78960c',
    messagingSenderId: '813007988453',
    projectId: 'koroauth',
    authDomain: 'koroauth.firebaseapp.com',
    storageBucket: 'koroauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8XSKNJO0nKTjF164dmvdIw2qxf_K2xb4',
    appId: '1:813007988453:android:6fabdc70760238d878960c',
    messagingSenderId: '813007988453',
    projectId: 'koroauth',
    storageBucket: 'koroauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOcOZMYbFh_6BGqrJOcbPCxTdROcfAPVk',
    appId: '1:813007988453:ios:0670da517c3336bb78960c',
    messagingSenderId: '813007988453',
    projectId: 'koroauth',
    storageBucket: 'koroauth.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOcOZMYbFh_6BGqrJOcbPCxTdROcfAPVk',
    appId: '1:813007988453:ios:a755e331fbc617a978960c',
    messagingSenderId: '813007988453',
    projectId: 'koroauth',
    storageBucket: 'koroauth.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
